// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbrepo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AssignRoleToMember(ctx context.Context, arg AssignRoleToMemberParams) error
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateProjectMember(ctx context.Context, arg CreateProjectMemberParams) (ProjectMember, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetMemberRoles(ctx context.Context, memberID pgtype.UUID) ([]GetMemberRolesRow, error)
	GetProjectByCode(ctx context.Context, projectCode string) (Project, error)
	GetRefreshTokenByID(ctx context.Context, id pgtype.UUID) (RefreshToken, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByRut(ctx context.Context, rut int32) (User, error)
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error
	RevokeRefreshToken(ctx context.Context, id pgtype.UUID) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error)
}

var _ Querier = (*Queries)(nil)
